sudo: required
dist: trusty
language: c
services: docker

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
            - cppcheck
      env: CXX=g++-4.9 CC=gcc-4.9 MODE=Debug COVERAGE=TRUE CPPCHECK=TRUE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env: CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env: CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env: CXX=clang++-3.6 CC=clang-3.6 MODE=Release TESTS_VALGRIND=TRUE
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3

before_install:
  - git clone https://github.com/dockcross/dockcross.git

script:
  - echo -- compile for linux-x64 platform
  - docker run --rm dockcross/linux-x64 > ./dockcross-linux-x64
  - chmod +x ./dockcross-linux-x64
  - ./dockcross-linux-x64 bash -c 'curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/ci.sh | bash'
  - echo -- compile for linux-armv7 platform
  - docker run --rm dockcross/linux-armv7 > ./dockcross-linux-armv7
  - chmod +x ./dockcross-linux-armv7
  - ./dockcross-linux-armv7 bash -c 'curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/ci.sh | bash'
