sudo: required
dist: trusty
language: c
cache: ccache
services: docker

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
            - cppcheck
      env: CXX=g++-4.9 CC=gcc-4.9 MODE=Debug COVERAGE=TRUE CPPCHECK=TRUE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env: CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env: CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env: CXX=clang++-3.6 CC=clang-3.6 MODE=Release TESTS_VALGRIND=TRUE
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3

script:
  - git clone https://github.com/makiolo/cmaki_identifier.git
  - (cd cmaki_identifier && CMAKI_PWD=$(pwd) CMAKI_INSTALL=$(pwd)/../node_modules/cmaki/ci npm install)
  - cp $(pwd)/node_modules/cmaki/ci/$MODE/* $(pwd)/node_modules/cmaki/ci
  - find $(pwd)/node_modules/cmaki/ci
  - export USE_CMAKI_IDENTIFIER=TRUE
  - bash <(curl -s https://raw.githubusercontent.com/makiolo/cmaki/master/ci.sh)

