sudo: required
dist: trusty
language: c
services: docker
os: linux
env:
  - IMAGE=android-arm
  - IMAGE=browser-asmjs
  - IMAGE=windows-x86
  - IMAGE=windows-x64
  - IMAGE=linux-x86
  - IMAGE=linux-x64

before_install:
  - git clone https://github.com/dockcross/dockcross.git

script:
  - 
    |
      docker run --rm dockcross/$IMAGE > ./dockcross-$IMAGE
      echo ------------------
      cat ./dockcross-$IMAGE
      echo ------------------
      chmod +x ./dockcross-$IMAGE
      ./dockcross-$IMAGE bash -c 'echo DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE} && echo ---------------'
      ./dockcross-$IMAGE bash -c 'cat ${CMAKE_TOOLCHAIN_FILE}'
      ./dockcross-$IMAGE bash -c 'curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/ci.sh | bash'
