language: cpp

os:
  - linux
  - osx

before_install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then
        sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
        sudo add-apt-repository --yes ppa:h-rayflood/llvm;
        sudo add-apt-repository --yes ppa:andykimpe/cmake;
        sudo apt-get update -qq;
        sudo apt-get install -qq cmake;
        sudo apt-get install -qq $SUPPORT;
        sudo apt-get install -qq $PACKAGE;
    fi

  #setup compiler
  - export CC=${REAL_CC} CXX=${REAL_CXX}

script:
  - mkdir -p $FL_CONF
  - cd $FL_CONF
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$FL_CONF
  - make
  - make test

env:
  - ignore=this

matrix:
  exclude:
    - env: ignore=this
  include:
#clang-3.2
##Debug
    - compiler: clang
      env: REAL_CC=clang-3.2 REAL_CXX=clang++-3.2 PACKAGE=clang-3.2 SUPPORT=g++-4.8 FL_CONF=Debug EXTRA_DEF=-std=c++14

##Release
    - compiler: clang
      env: REAL_CC=clang-3.2 REAL_CXX=clang++-3.2 PACKAGE=clang-3.2 SUPPORT=g++-4.8 FL_CONF=Release EXTRA_DEF=-std=c++14

#clang-3.3
##Debug
    - compiler: clang
      env: REAL_CC=clang-3.3 REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8 FL_CONF=Debug EXTRA_DEF=-std=c++14

##Release
    - compiler: clang
      env: REAL_CC=clang-3.3 REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8 FL_CONF=Release EXTRA_DEF=-std=c++14

#clang-3.4
##Debug
    - compiler: clang
      env: REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8 FL_CONF=Debug EXTRA_DEF=-std=c++14

##Release
    - compiler: clang
      env: REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8 FL_CONF=Release EXTRA_DEF=-std=c++14

#gcc-4.7
##Debug
    - compiler: clang
      env: REAL_CC=gcc-4.7   REAL_CXX=g++-4.7     PACKAGE=g++-4.7   SUPPORT=    FL_CONF=Debug EXTRA_DEF=-std=c++14

##Release
    - compiler: clang
      env: REAL_CC=gcc-4.7   REAL_CXX=g++-4.7     PACKAGE=g++-4.7   SUPPORT=    FL_CONF=Release EXTRA_DEF=-std=c++14

#gcc-4.8
##Debug
    - compiler: clang
      env: REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=    FL_CONF=Debug EXTRA_DEF=-std=c++14
      
##Release
    - compiler: clang
      env: REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=    FL_CONF=Release EXTRA_DEF=-std=c++14

notifications:
  email:
    recipients:
      - makiolo@gmail.com
    on_success: change
    on_failure: always

