language: c
services: docker
os: linux
env:
  # - IMAGE=linux-x86
  - IMAGE=linux-x64
  - IMAGE=windows-x86
  - IMAGE=windows-x64
  # - IMAGE=android-arm
  # - IMAGE=browser-asmjs
  # - IMAGE=linux-x86 MODE=Release
  - IMAGE=linux-x64 MODE=Release
  - IMAGE=windows-x86 MODE=Release
  - IMAGE=windows-x64 MODE=Release
  # - IMAGE=android-arm MODE=Release
  # - IMAGE=browser-asmjs MODE=Release
script:
  - npm run docker
