sudo: required
dist: trusty
language: c
services: docker
os: linux
env:
  # - IMAGE=windows-x86
  # - IMAGE=windows-x64
  # - IMAGE=linux-x86
  - IMAGE=linux-x64
  # - IMAGE=android-arm
  # - IMAGE=browser-asmjs

script:
  # - bash <(curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/ci.sh)
  - bash <(curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/docker.sh)

