sudo: required
dist: trusty
language: c
services: docker
os: linux
env:
  - IMAGE=windows-x86
  - IMAGE=windows-x64
  - IMAGE=linux-x86
  - IMAGE=linux-x64
  - IMAGE=android-arm
  - IMAGE=browser-asmjs

before_install:
  - git clone https://github.com/dockcross/dockcross.git

script:
  - 
    |
      sudo docker run --rm dockcross/$IMAGE > ./dockcross-$IMAGE
      chmod +x ./dockcross-$IMAGE
      export CMAKI_EMULATOR=$(sudo ./dockcross-$IMAGE bash -c 'echo "message(\${CMAKE_CROSSCOMPILING_EMULATOR})" >> ${CMAKE_TOOLCHAIN_FILE} && cmake -P ${CMAKE_TOOLCHAIN_FILE}')
      sudo ./dockcross-$IMAGE -a "-e CMAKI_EMULATOR=$CMAKI_EMULATOR" bash -c 'curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/ci.sh | bash'

