language: c
services: docker
os: linux
env:
  - IMAGE=windows-x64
  - IMAGE=linux-x64
script:
  - bash <(curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/docker.sh)

# - IMAGE=windows-x86
# - IMAGE=windows-x64
# - IMAGE=linux-x86
# - IMAGE=linux-x64
# - IMAGE=android-arm
# - IMAGE=browser-asmjs

