version: 0.1.{build}

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: pip install pyyaml
  - cmd: pip install poster

build_script:
  - cmd: npm install
