version: 1.0.0.{build}

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build: off
install:
  - cmd: choco install curl
  - cmd: curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/ci.cmd > ci.cmd
  - cmd: call ci.cmd
  - cmd: exit /b %errorlevel%
